# Generated by Django 3.2.4 on 2021-06-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(blank=True, choices=[('None', 'None'), ('AWS Certified Solutions Architect', 'AWS Certified Solutions Architect'), ('AWS Certified Developer', 'AWS Certified Developer'), ('ScrumMaster', 'ScrumMaster'), ('Certified Information Systems Security Professional', 'Certified Information Systems Security Professional'), ('Certified in Risk and Information Systems Control', 'Certified in Risk and Information Systems Control'), ('Certified Ethical Hacker', 'Certified Ethical Hacker'), ('Citrix Certified Associate — Virtualization', 'Citrix Certified Associate — Virtualization'), ('Google Certified Professional Cloud Architect', 'Google Certified Professional Cloud Architect'), ('IT project management', 'IT project management'), ('Microsoft Certified Professionals Certifications', 'Microsoft Certified Professionals Certifications')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Business Administration', 'Business Administration'), ('International Studies', 'International Studies'), ('Natural Sciences', 'Natural Sciences')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, choices=[('FRESHMAN', 'FRESHMAN'), ('SOPHMORE', 'SOPHMORE'), ('JUNIOR', 'JUNIOR'), ('SENIOR', 'SENIOR'), ('UNKNOWN', 'UNKNOWN')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('year_of_graduation', models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('Unknown', 'Unknown')], max_length=15)),
                ('department', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='student_dept', to='student.department')),
                ('grade', models.ForeignKey(default='Unknown', max_length=50, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='student_grade', to='student.grade')),
                ('school', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='student.school')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('school_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.faculty'),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='student.certificate_type')),
                ('fullname', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certif_student', to='student.student_record')),
            ],
        ),
    ]
