# Generated by Django 3.2.4 on 2021-06-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='fullname',
            new_name='name',
        ),
    ]
